# GitHub Actions Workflow responsible for cleaning up the Composite Action Template repository from the template-specific files and configurations.
# This workflow is supposed to be triggered automatically when a new template-based repository has been created.

name: Template Cleanup

on:
  push:
    branches:
      - main

jobs:
  # Run a cleaning process only if the workflow is triggered by the non-"composite-action-template" repository.
  template-cleanup:
    name: Template Cleanup

    runs-on: ubuntu-latest

    if: github.event.repository.name != 'composite-action-template'

    permissions:
      contents: write
      actions: write

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Get repository description
        id: get_description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DESCRIPTION=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}" | jq -r .description)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_OUTPUT

      - name: Replace placeholders using script
        run: |
          # Get the repository name and author
          NAME=$(basename $GITHUB_REPOSITORY)
          AUTHOR_ID=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)

          # Replace placeholders in README template
          sed -e "s/%NAME%/$NAME/g" \
              -e "s/%AUTHOR%/$AUTHOR_ID/g" \
              -e "s/%DESCRIPTION%/$DESCRIPTION/g" \
              templates/README.md > README.md

          # Replace placeholders in action.yml template
          sed -e "s/%NAME%/$NAME/g" \
              -e "s/%AUTHOR%/$AUTHOR_ID/g" \
              -e "s/%DESCRIPTION%/$DESCRIPTION/g" \
              templates/action.yml > action.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESCRIPTION: ${{ steps.get_description.outputs.DESCRIPTION }}

      - name: Remove Files
        run: |
          rm -rf templates LICENSE .github/workflows/template-cleanup.yml CHANGELOG.md .github/FUNDING.yml

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "chore: Template cleanup"
          git push origin main
